app:
  title: Red Hat Developer Hub
integrations:
  github:
    - host: github.com
      #token: ${GITHUB_TOKEN}
catalog:
  processingInterval: { minutes: 5 }
  providers:
    keycloakOrg:
      default:
        baseUrl: https://keycloak-${RHDH_NAMESPACE}.${OPENSHIFT_APP_DOMAIN}/auth
        realm: backstage
        loginRealm: backstage
        clientId: backstage
        clientSecret: ${KEYCLOAK_CLIENT_SECRET}
enabled:
  github: true
  keycloak: true
