app:
  title: Red Hat Developer Hub
integrations:
  github:
    - host: github.com
      #token: ${GITHUB_TOKEN}
catalog:
  processingInterval: { minutes: 5 }
  providers:
    keycloakOrg:
      default:
        baseUrl: ${KEYCLOAK_BASE_URL}
        realm: ${KEYCLOAK_REALM}
        loginRealm: ${KEYCLOAK_LOGIN_REALM}
        clientId: ${CLIENT_ID}
        clientSecret: ${CLIENT_SECRET}
        userQuerySize: 1000
        groupQuerySize: 1000
        schedule:
          frequency: { seconds: 30 }
          timeout: { minutes: 1 }
          initialDelay: { seconds: 15 }
enabled:
  github: true
  keycloak: true
