kind: ConfigMap
apiVersion: v1
metadata:
  name: rbac-policy
data:
  rbac-policy.csv: |
    p, role:default/a, kubernetes.proxy, use, allow
    p, role:default/a, catalog-entity, read, allow
    p, role:default/a, catalog.entity.create, create, allow
    p, role:default/a, catalog.location.create, create, allow
    p, role:default/a, catalog.location.read, read, allow
    g, user:default/guru, role:default/a
    g, user:development/guest, role:default/a
