{% macro pv_stats(pvc) -%}
# Collect data for PV stats
- name: measurements.cluster.pv_stats.populate.{{pvc}}.capacity_bytes
  monitoring_query: kubelet_volume_stats_capacity_bytes{persistentvolumeclaim="{{ pvc }}"}
  monitoring_step: 15
- name: measurements.cluster.pv_stats.populate.{{pvc}}.used_bytes
  monitoring_query: kubelet_volume_stats_used_bytes{persistentvolumeclaim="{{ pvc }}"}
  monitoring_step: 15
- name: measurements.cluster.pv_stats.populate.{{pvc}}.available_bytes
  monitoring_query: kubelet_volume_stats_available_bytes{persistentvolumeclaim="{{ pvc }}"}
  monitoring_step: 15
{%- endmacro %}

{{ pv_stats('data-rhdh-postgresql-primary-0') }}
