image:
  repository: "quay.io/backstage-performance/locust-k8s-operator"
  tag: "latest"

config:
  loadGenerationPods:
    resource:
      cpuRequest: 250m
      memRequest: 128Mi
      ephemeralRequest: 30Mi
      cpuLimit: 2000m
      memLimit: 2Gi
      ephemeralLimit: 100Mi
    metricsExporter:
      image: "quay.io/backstage-performance/locust_exporter:latest"
