image:
  repository: "quay.io/backstage-performance/locust-k8s-operator"
  tag: "latest"

config:
  loadGenerationPods:
    resource:
      cpuRequest: 250m
      memRequest: 128Mi
      ephemeralRequest: 30M
      cpuLimit: 1000m
      memLimit: 1024Mi
      ephemeralLimit: 50M
    metricsExporter:
      image: "quay.io/backstage-performance/locust_exporter:latest"
