apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: guru
  labels:
    app: sso
spec:
  realmSelector:
    matchLabels:
      app: sso
  user:
    username: guru
    firstName: Guru
    lastName: RHDH Admin
    email: guru@test.com
    enabled: true
    emailVerified: true
    temporary: false
    credentials:
      - type: password
        value: ${KEYCLOAK_USER_PASS}
