name: PR checks

on:
  pull_request:
    branches:
      - main

env: {}

jobs:
  lint:
    name: Code Quality
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run linters
        run: make lint

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
